# Generated by Django 3.2 on 2021-05-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0003_alter_episode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-id']},
        ),
    ]
